services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api-server/.env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  worker-server:
    build:
      context: ./worker-server
      dockerfile: Dockerfile
    env_file:
      - ./worker-server/.env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

volumes:
  redis-data: 